package com.lonch.client.databases;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lonch.client.database.bean.SmallVideoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "lonch_video_entity".
*/
public class SmallVideoEntityDao extends AbstractDao<SmallVideoEntity, Long> {

    public static final String TABLENAME = "lonch_video_entity";

    /**
     * Properties of entity SmallVideoEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property VideoId = new Property(1, String.class, "videoId", false, "VIDEO_ID");
        public final static Property StartTime = new Property(2, Long.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(3, Long.class, "endTime", false, "END_TIME");
        public final static Property LeaveVideoTime = new Property(4, Long.class, "leaveVideoTime", false, "LEAVE_VIDEO_TIME");
        public final static Property IsLeaveActive = new Property(5, int.class, "isLeaveActive", false, "IS_LEAVE_ACTIVE");
        public final static Property IsForward = new Property(6, int.class, "isForward", false, "IS_FORWARD");
    }


    public SmallVideoEntityDao(DaoConfig config) {
        super(config);
    }
    
    public SmallVideoEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"lonch_video_entity\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"VIDEO_ID\" TEXT," + // 1: videoId
                "\"START_TIME\" INTEGER," + // 2: startTime
                "\"END_TIME\" INTEGER," + // 3: endTime
                "\"LEAVE_VIDEO_TIME\" INTEGER," + // 4: leaveVideoTime
                "\"IS_LEAVE_ACTIVE\" INTEGER NOT NULL ," + // 5: isLeaveActive
                "\"IS_FORWARD\" INTEGER NOT NULL );"); // 6: isForward
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"lonch_video_entity\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SmallVideoEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String videoId = entity.getVideoId();
        if (videoId != null) {
            stmt.bindString(2, videoId);
        }
 
        Long startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindLong(3, startTime);
        }
 
        Long endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(4, endTime);
        }
 
        Long leaveVideoTime = entity.getLeaveVideoTime();
        if (leaveVideoTime != null) {
            stmt.bindLong(5, leaveVideoTime);
        }
        stmt.bindLong(6, entity.getIsLeaveActive());
        stmt.bindLong(7, entity.getIsForward());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SmallVideoEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String videoId = entity.getVideoId();
        if (videoId != null) {
            stmt.bindString(2, videoId);
        }
 
        Long startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindLong(3, startTime);
        }
 
        Long endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(4, endTime);
        }
 
        Long leaveVideoTime = entity.getLeaveVideoTime();
        if (leaveVideoTime != null) {
            stmt.bindLong(5, leaveVideoTime);
        }
        stmt.bindLong(6, entity.getIsLeaveActive());
        stmt.bindLong(7, entity.getIsForward());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SmallVideoEntity readEntity(Cursor cursor, int offset) {
        SmallVideoEntity entity = new SmallVideoEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // videoId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // startTime
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // endTime
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // leaveVideoTime
            cursor.getInt(offset + 5), // isLeaveActive
            cursor.getInt(offset + 6) // isForward
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SmallVideoEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVideoId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStartTime(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setEndTime(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setLeaveVideoTime(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setIsLeaveActive(cursor.getInt(offset + 5));
        entity.setIsForward(cursor.getInt(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SmallVideoEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SmallVideoEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SmallVideoEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
